-- MySQL Script generated by MySQL Workbench
-- Wed Mar  1 14:23:34 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`UserCreds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserCreds` (
  `UserID` VARCHAR(50) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserID`, `Password`),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserInfo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserInfo` (
  `UserID` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(80) NOT NULL,
  `Bio` LONGTEXT NULL,
  `Pic` BLOB NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  CONSTRAINT `UserID`
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb`.`UserCreds` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UserFundLink`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UserFundLink` (
  `UserID` VARCHAR(80) NOT NULL,
  `FundName` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `FundName_UNIQUE` (`FundName` ASC) VISIBLE,
  CONSTRAINT `UserID1`
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb`.`UserCreds` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Funds`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Funds` (
  `FundName` VARCHAR(80) NOT NULL,
  `FundType` VARCHAR(45) NOT NULL,
  `FundGoal` INT NOT NULL,
  `FundRaised` DECIMAL ZEROFILL NOT NULL,
  PRIMARY KEY (`FundName`),
  UNIQUE INDEX `FundName_UNIQUE` (`FundName` ASC) VISIBLE,
  CONSTRAINT `FundName1`
    FOREIGN KEY (`FundName`)
    REFERENCES `mydb`.`UserFundLink` (`FundName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Donations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Donations` (
  `FundName` VARCHAR(80) NOT NULL,
  `UserID` VARCHAR(80) NULL,
  `DonoAmount` DECIMAL NOT NULL,
  `DonoTime` DATE NOT NULL,
  PRIMARY KEY (`FundName`),
  INDEX `UserID_idx` (`UserID` ASC) VISIBLE,
  CONSTRAINT `FundName`
    FOREIGN KEY (`FundName`)
    REFERENCES `mydb`.`UserFundLink` (`FundName`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `UserID2`
    FOREIGN KEY (`UserID`)
    REFERENCES `mydb`.`UserCreds` (`UserID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
